# Generated by Django 5.2.5 on 2025-09-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='locations_s_name_5adbc5_idx'), models.Index(fields=['code'], name='locations_s_code_f8d7d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='locations_d_name_f8f0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['state', 'name'], name='locations_d_state_i_19ead7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='locations_c_name_5719ba_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['district', 'name'], name='locations_c_distric_5bbfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'name'], name='locations_c_state_i_eef7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['pincode'], name='locations_c_pincode_630de2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'district')},
        ),
    ]
