# Generated by Django 5.2.5 on 2025-09-02 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('listings', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, to='listings.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state', 'district'], name='accounts_us_state_i_4f3a17_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='accounts_us_is_veri_fa45d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rating'], name='accounts_us_rating_658e53_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active'], name='accounts_us_last_ac_e71e88_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollowing',
            index=models.Index(fields=['follower'], name='accounts_us_followe_c026cb_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollowing',
            index=models.Index(fields=['following'], name='accounts_us_followi_39a49a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['rated_user', 'rating'], name='accounts_us_rated_u_a569c9_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['created_at'], name='accounts_us_created_79d295_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('rater', 'rated_user', 'transaction_id')},
        ),
    ]
